export const iphones = [
    {
        id: 101,
        name: 'iPhone 16 Pro Max',
        year_introduced: '2024',
        storage_options: ['256GB', '512GB', '1TB'],
        colors: ['Black Titanium', 'White Titanium', 'Natural Titanium', 'Desert Titanium'],
        description: 'The ultimate iPhone experience. Features a 6.9-inch Super Retina XDR display with Dynamic Island, A18 Pro chip, advanced Pro camera system with new Camera Control, and contoured-edge titanium design.',
        price_range: '$1199 - $1699', // Estimated based on current pricing patterns
        imageUrl: 'https://placehold.co/600x400/000000/FFFFFF?text=iPhone+16+Pro+Max',
        detailsLink: '/iphone-16-pro-max-details',
    },
    {
        id: 102,
        name: 'iPhone 16 Pro',
        year_introduced: '2024',
        storage_options: ['128GB', '256GB', '512GB', '1TB'],
        colors: ['Black Titanium', 'White Titanium', 'Natural Titanium', 'Desert Titanium'],
        description: 'Packed with cutting-edge features. Boasts a 6.3-inch Super Retina XDR display with Dynamic Island, A18 Pro chip, and the powerful Pro camera system.',
        price_range: '$999 - $1499',
        imageUrl: 'https://placehold.co/600x400/000000/FFFFFF?text=iPhone+16+Pro',
        detailsLink: '/iphone-16-pro-details',
    },
    {
        id: 103,
        name: 'iPhone 16',
        year_introduced: '2024',
        storage_options: ['128GB', '256GB', '512GB'],
        colors: ['Ultramarine', 'Teal', 'Pink', 'White', 'Black'],
        description: 'A total powerhouse with advanced camera features. Features a 6.1-inch Super Retina XDR display, A18 chip, and advanced dual-camera system.',
        price_range: '$799 - $1099',
        imageUrl: 'https://placehold.co/600x400/000000/FFFFFF?text=iPhone+16',
        detailsLink: '/iphone-16-details',
    },
    {
        id: 104,
        name: 'iPhone 16e',
        year_introduced: '2025', // Anticipated release
        storage_options: ['128GB', '256GB', '512GB'],
        colors: ['Black', 'White'],
        description: 'The latest iPhone at a great price. Features a 6.1-inch Super Retina XDR OLED display and A18 chip.',
        price_range: '$599 - $799',
        imageUrl: 'https://placehold.co/600x400/000000/FFFFFF?text=iPhone+16e',
        detailsLink: '/iphone-16e-details',
    },
    {
        id: 105,
        name: 'iPhone 15',
        year_introduced: '2023',
        storage_options: ['128GB', '256GB', '512GB'],
        colors: ['Pink', 'Yellow', 'Green', 'Blue', 'Black'],
        description: 'Still an amazing iPhone. Features a 6.1-inch Super Retina XDR display with Dynamic Island, A16 Bionic chip, and 48MP Main camera.',
        price_range: '$699 - $999',
        imageUrl: 'https://placehold.co/600x400/000000/FFFFFF?text=iPhone+15',
        detailsLink: '/iphone-15-details',
    },
];

export const macs = [
    {
        id: 201,
        name: 'MacBook Air 13-inch (M4)',
        year_introduced: '2025', // Anticipated release
        storage_options: ['256GB', '512GB', '1TB', '2TB'],
        colors: ['Midnight', 'Starlight', 'Space Gray', 'Silver'],
        description: 'Strikingly thin and fast, powered by the M4 chip. Perfect for everyday productivity and creativity.',
        price_range: '$1099 - $2099',
        imageUrl: 'https://placehold.co/600x400/000000/FFFFFF?text=MacBook+Air+13+M4',
        detailsLink: '/macbook-air-13-m4-details',
    },
    {
        id: 202,
        name: 'MacBook Air 15-inch (M4)',
        year_introduced: '2025', // Anticipated release
        storage_options: ['256GB', '512GB', '1TB', '2TB'],
        colors: ['Midnight', 'Starlight', 'Space Gray', 'Silver'],
        description: 'More screen for more possibilities, supercharged by the M4 chip. Ideal for multitasking and immersive experiences.',
        price_range: '$1299 - $2299',
        imageUrl: 'https://placehold.co/600x400/000000/FFFFFF?text=MacBook+Air+15+M4',
        detailsLink: '/macbook-air-15-m4-details',
    },
    {
        id: 203,
        name: 'MacBook Pro 14-inch (M4 Pro/Max)',
        year_introduced: '2024',
        storage_options: ['512GB', '1TB', '2TB', '4TB', '8TB'],
        colors: ['Space Black', 'Silver'],
        description: 'Unrivaled performance for pro workflows, featuring the M4 Pro or M4 Max chip and a stunning Liquid Retina XDR display.',
        price_range: '$1699 - $3999+',
        imageUrl: 'https://placehold.co/600x400/000000/FFFFFF?text=MacBook+Pro+14+M4',
        detailsLink: '/macbook-pro-14-m4-details',
    },
    {
        id: 204,
        name: 'MacBook Pro 16-inch (M4 Pro/Max)',
        year_introduced: '2024',
        storage_options: ['512GB', '1TB', '2TB', '4TB', '8TB'],
        colors: ['Space Black', 'Silver'],
        description: 'The ultimate portable workstation, powered by the M4 Pro or M4 Max chip for extreme performance and an expansive Liquid Retina XDR display.',
        price_range: '$2499 - $4999+',
        imageUrl: 'https://placehold.co/600x400/000000/FFFFFF?text=MacBook+Pro+16+M4',
        detailsLink: '/macbook-pro-16-m4-details',
    },
    {
        id: 205,
        name: 'iMac (M4)',
        year_introduced: '2025', // Anticipated release
        storage_options: ['256GB', '512GB', '1TB', '2TB'],
        colors: ['Blue', 'Green', 'Pink', 'Silver', 'Yellow', 'Orange', 'Purple'],
        description: 'A stunning all-in-one desktop with a vibrant 24-inch 4.5K Retina display, now even more powerful with the M4 chip.',
        price_range: '$1299 - $2099',
        imageUrl: 'https://placehold.co/600x400/000000/FFFFFF?text=iMac+M4',
        detailsLink: '/imac-m4-details',
    },
    {
        id: 206,
        name: 'Mac mini (M4)',
        year_introduced: '2025', // Anticipated release
        storage_options: ['256GB', '512GB', '1TB', '2TB'],
        colors: ['Silver', 'Space Gray'],
        description: 'The versatile mini desktop, now with the mighty M4 chip for impressive performance in a compact design.',
        price_range: '$599 - $1499',
        imageUrl: 'https://placehold.co/600x400/000000/FFFFFF?text=Mac+mini+M4',
        detailsLink: '/mac-mini-m4-details',
    },
    {
        id: 207,
        name: 'Mac Studio (M4 Max/Ultra)',
        year_introduced: '2025', // Anticipated release
        storage_options: ['512GB', '1TB', '2TB', '4TB', '8TB'],
        colors: ['Silver'],
        description: 'Unleash extreme power for demanding workflows, featuring the M4 Max or M4 Ultra chip and extensive connectivity.',
        price_range: '$1999 - $7999+',
        imageUrl: 'https://placehold.co/600x400/000000/FFFFFF?text=Mac+Studio+M4',
        detailsLink: '/mac-studio-m4-details',
    },
    {
        id: 208,
        name: 'Mac Pro (M2 Ultra)', // M4 Ultra is anticipated, but M2 Ultra is current top
        year_introduced: '2023',
        storage_options: ['1TB', '2TB', '4TB', '8TB'],
        colors: ['Silver'],
        description: 'The ultimate modular workstation with PCIe expansion, powered by the M2 Ultra chip for unparalleled performance.',
        price_range: '$6999 - $15999+',
        imageUrl: 'https://placehold.co/600x400/000000/FFFFFF?text=Mac+Pro+M2+Ultra',
        detailsLink: '/mac-pro-m2-ultra-details',
    },
];

export const iPads = [
    {
        id: 301,
        name: 'iPad Pro 13-inch (M4)',
        year_introduced: '2024',
        storage_options: ['256GB', '512GB', '1TB', '2TB'],
        colors: ['Space Black', 'Silver'],
        description: 'The thinnest Apple product ever, with a groundbreaking Ultra Retina XDR display and the incredibly powerful M4 chip.',
        price_range: '$1299 - $2599+',
        imageUrl: 'https://placehold.co/600x400/000000/FFFFFF?text=iPad+Pro+13+M4',
        detailsLink: '/ipad-pro-13-m4-details',
    },
    {
        id: 302,
        name: 'iPad Pro 11-inch (M4)',
        year_introduced: '2024',
        storage_options: ['256GB', '512GB', '1TB', '2TB'],
        colors: ['Space Black', 'Silver'],
        description: 'Stunning performance and a brilliant Ultra Retina XDR display, powered by the M4 chip in a portable 11-inch design.',
        price_range: '$999 - $2299+',
        imageUrl: 'https://placehold.co/600x400/000000/FFFFFF?text=iPad+Pro+11+M4',
        detailsLink: '/ipad-pro-11-m4-details',
    },
    {
        id: 303,
        name: 'iPad Air 13-inch (M3)',
        year_introduced: '2025', // Anticipated release
        storage_options: ['128GB', '256GB', '512GB', '1TB'],
        colors: ['Space Gray', 'Starlight', 'Blue', 'Purple'],
        description: 'More screen, more power. Now supercharged by the M3 chip with a 13-inch Liquid Retina display.',
        price_range: '$799 - $1499',
        imageUrl: 'https://placehold.co/600x400/000000/FFFFFF?text=iPad+Air+13+M3',
        detailsLink: '/ipad-air-13-m3-details',
    },
    {
        id: 304,
        name: 'iPad Air 11-inch (M3)',
        year_introduced: '2025', // Anticipated release
        storage_options: ['128GB', '256GB', '512GB', '1TB'],
        colors: ['Space Gray', 'Starlight', 'Blue', 'Purple'],
        description: 'The versatile iPad Air, now with the M3 chip for enhanced performance and a beautiful 11-inch Liquid Retina display.',
        price_range: '$599 - $1299',
        imageUrl: 'https://placehold.co/600x400/000000/FFFFFF?text=iPad+Air+11+M3',
        detailsLink: '/ipad-air-11-m3-details',
    },
    {
        id: 305,
        name: 'iPad (10th Generation)',
        year_introduced: '2022',
        storage_options: ['64GB', '256GB'],
        colors: ['Blue', 'Pink', 'Yellow', 'Silver'],
        description: 'The colorful and capable iPad for everyday use, with an all-screen design and A14 Bionic chip.',
        price_range: '$349 - $549',
        imageUrl: 'https://placehold.co/600x400/000000/FFFFFF?text=iPad+10th+Gen',
        detailsLink: '/ipad-10th-gen-details',
    },
    {
        id: 306,
        name: 'iPad mini (A17 Pro)',
        year_introduced: '2024',
        storage_options: ['128GB', '256GB', '512GB'],
        colors: ['Space Gray', 'Starlight', 'Pink', 'Purple'],
        description: 'The compact powerhouse, now with the A17 Pro chip for incredible performance in a pocketable design.',
        price_range: '$499 - $849',
        imageUrl: 'https://placehold.co/600x400/000000/FFFFFF?text=iPad+Mini+A17+Pro',
        detailsLink: '/ipad-mini-a17-pro-details',
    },
];

export const appleWatches = [
    {
        id: 401,
        name: 'Apple Watch Ultra 2',
        year_introduced: '2023',
        case_materials: ['Titanium'],
        connectivity: ['GPS + Cellular'],
        description: 'The most rugged and capable Apple Watch, designed for extreme adventures with a brighter display and advanced health features.',
        price_range: '$799 - $849',
        imageUrl: 'https://placehold.co/600x400/000000/FFFFFF?text=Apple+Watch+Ultra+2',
        detailsLink: '/apple-watch-ultra-2-details',
    },
    {
        id: 402,
        name: 'Apple Watch Series 10',
        year_introduced: '2024', // Anticipated release
        case_materials: ['Aluminum', 'Stainless Steel'],
        connectivity: ['GPS', 'GPS + Cellular'],
        description: 'The latest mainstream Apple Watch with advanced health sensors, new features, and a stunning display.',
        price_range: '$399 - $749',
        imageUrl: 'https://placehold.co/600x400/000000/FFFFFF?text=Apple+Watch+Series+10',
        detailsLink: '/apple-watch-series-10-details',
    },
    {
        id: 403,
        name: 'Apple Watch SE (2nd Gen)',
        year_introduced: '2022',
        case_materials: ['Aluminum'],
        connectivity: ['GPS', 'GPS + Cellular'],
        description: 'All the essentials of Apple Watch at an even more affordable price, with powerful features for fitness and safety.',
        price_range: '$249 - $299',
        imageUrl: 'https://placehold.co/600x400/000000/FFFFFF?text=Apple+Watch+SE+2nd+Gen',
        detailsLink: '/apple-watch-se-2nd-gen-details',
    },
];

export const airpods = [
    {
        id: 501,
        name: 'AirPods Max',
        year_introduced: '2020',
        colors: ['Space Gray', 'Silver', 'Sky Blue', 'Pink', 'Green'],
        description: 'The ultimate over-ear listening experience with high-fidelity audio, Active Noise Cancellation, and Transparency mode.',
        price_range: '$549',
        imageUrl: 'https://placehold.co/600x400/000000/FFFFFF?text=AirPods+max',
        detailsLink: '/airpods-max-details',
    },
    {
        id: 502,
        name: 'AirPods Pro (2nd Gen) with USB-C',
        year_introduced: '2023',
        description: 'Up to 2x more Active Noise Cancellation, Adaptive Audio, Conversation Awareness, and Spatial Audio, now with USB-C charging.',
        price_range: '$249',
        imageUrl: 'https://placehold.co/600x400/000000/FFFFFF?text=AirPods+Pro+2nd+Gen+USB-C',
        detailsLink: '/airpods-pro-2nd-gen-usb-c-details',
    },
    {
        id: 503,
        name: 'AirPods (4th Gen) with ANC',
        year_introduced: '2024', // Anticipated release
        description: 'Iconic design, now with Active Noise Cancellation, H2 chip, and an improved acoustic experience.',
        price_range: '$179',
        imageUrl: 'https://placehold.co/600x400/000000/FFFFFF?text=AirPods+4th+Gen+ANC',
        detailsLink: '/airpods-4th-gen-anc-details',
    },
    {
        id: 504,
        name: 'AirPods (4th Gen)',
        year_introduced: '2024', // Anticipated release
        description: 'Iconic. Now supersonic. H2 chip, Personalized Spatial Audio, and longer battery life.',
        price_range: '$129',
        imageUrl: 'https://placehold.co/600x400/000000/FFFFFF?text=AirPods+4th+Gen',
        detailsLink: '/airpods-4th-gen-details',
    },
];

export const appleTVs = [
    {
        id: 601,
        name: 'Apple TV 4K (3rd Gen)',
        year_introduced: '2022',
        storage_options: ['64GB', '128GB'],
        description: 'The best way to experience Apple TV+ and all your favorite streaming services in stunning 4K HDR. Features the A15 Bionic chip and Siri Remote.',
        price_range: '$129 - $149',
        imageUrl: 'https://placehold.co/600x400/000000/FFFFFF?text=Apple+TV+4K+3rd+Gen',
        detailsLink: '/apple-tv-4k-3rd-gen-details',
    },
];

export const homepods = [
    {
        id: 701,
        name: 'HomePod (2nd Gen)',
        year_introduced: '2023',
        colors: ['Midnight', 'White'],
        description: 'Fill your room with rich, room-filling audio. Features Spatial Audio, temperature and humidity sensors, and acts as a smart home hub.',
        price_range: '$299',
        imageUrl: 'https://placehold.co/600x400/000000/FFFFFF?text=HomePod+2nd+Gen',
        detailsLink: '/homepod-2nd-gen-details',
    },
    {
        id: 702,
        name: 'HomePod mini',
        year_introduced: '2020',
        colors: ['Space Gray', 'White', 'Blue', 'Yellow', 'Orange', 'Midnight'],
        description: 'A small speaker with big sound. Features Siri, rich 360-degree audio, and smart home control.',
        price_range: '$99',
        imageUrl: 'https://placehold.co/600x400/000000/FFFFFF?text=HomePod+mini',
        detailsLink: '/homepod-mini-details',
    },
];

export const accessories = [
    {
        id: 801,
        name: 'AirTag',
        year_introduced: '2021',
        description: 'Keep track of your keys, wallet, luggage, backpack, and more. Play a sound on the built-in speaker, or use Precision Finding with UWB.',
        price_range: '$29 (single) / $99 (4-pack)',
        imageUrl: 'https://placehold.co/600x400/000000/FFFFFF?text=AirTag',
        detailsLink: '/airtag-details',
    },
    {
        id: 802,
        name: 'Apple Pencil Pro',
        year_introduced: '2024',
        description: 'All-new magical capabilities for taking notes, sketching, and marking up documents with even more control.',
        price_range: '$129',
        imageUrl: 'https://placehold.co/600x400/000000/FFFFFF?text=Apple+Pencil+Pro',
        detailsLink: '/apple-pencil-pro-details',
    },
    {
        id: 803,
        name: 'Magic Keyboard for iPad Pro',
        year_introduced: '2024',
        description: 'Incredible typing experience, a trackpad that opens up new ways to work, and front and back protection. Available for iPad Pro 11-inch and 13-inch.',
        price_range: '$299 - $349',
        imageUrl: 'https://placehold.co/600x400/000000/FFFFFF?text=Magic+Keyboard+iPad+Pro',
        detailsLink: '/magic-keyboard-ipad-pro-details',
    },
    {
        id: 804,
        name: 'Magic Keyboard with Touch ID and Numeric Keypad',
        year_introduced: '2021',
        description: 'Enables fast, secure authentication and a more productive typing experience on Mac models with Apple silicon.',
        price_range: '$199',
        imageUrl: 'https://placehold.co/600x400/000000/FFFFFF?text=Magic+Keyboard+Touch+ID',
        detailsLink: '/magic-keyboard-touch-id-details',
    },
    {
        id: 805,
        name: 'Magic Mouse',
        year_introduced: '2020',
        description: 'Wireless and rechargeable, with an optimized foot design that lets it glide smoothly across your desk. The Multi-Touch surface allows you to perform simple gestures.',
        price_range: '$79',
        imageUrl: 'https://placehold.co/600x400/000000/FFFFFF?text=Magic+Mouse',
        detailsLink: '/magic-mouse-details',
    },
    {
        id: 806,
        name: 'MagSafe Charger',
        year_introduced: '2020',
        description: 'Makes wireless charging a snap. The perfectly aligned magnets attach to your iPhone 12 or later and provide faster wireless charging up to 15W.',
        price_range: '$39',
        imageUrl: 'https://placehold.co/600x400/000000/FFFFFF?text=MagSafe+Charger',
        detailsLink: '/magsafe-charger-details',
    },
    {
        id: 807,
        name: 'Polishing Cloth',
        year_introduced: '2021',
        description: 'Made with soft, nonabrasive material, the Polishing Cloth cleans any Apple display, including nano-texture glass, safely and effectively.',
        price_range: '$19',
        imageUrl: 'https://placehold.co/600x400/000000/FFFFFF?text=Polishing+Cloth',
        detailsLink: '/polishing-cloth-details',
    },
];
